# .github/workflows/deploy.yml
name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4 # v3 -> v4に更新

      # 2. Railway CLIをインストールする
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # 3. Railwayにデプロイする
      #    RAILWAY_TOKENを環境変数として渡すことで、CLIが自動で認証を行う
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --detach
